{% set name = "setupmeta" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f13d6e3c4a5f1bbf06e41920eab36c05fd1de54cadb629f3a4d069e24a6503a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - setupmeta

about:
  home: https://github.com/codrsquad/setupmeta
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simplify your setup.py
  description: |
    Writing a setup.py typically involves lots of boilerplate and copy-pasting from project to project.
    This package aims to simplify that and bring some DRY principle to python packaging. For more
    information and examples, please refer to: https://github.com/zsimic/setupmeta.
    This package is only required to enable the building of Conda Python packages that
    make use of setupmeta (which is otherwise ordinarily installed dynamically
    as part of the setup.py workflows).
  doc_url: https://github.com/codrsquad/setupmeta
  dev_url: https://github.com/codrsquad/setupmeta

extra:
  recipe-maintainers:
    - zsimic
    - matthewwardrop
