{% set name = "setupmeta" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fedef994b83ee263daea0d1d5e4336880fea4a5ae26d06f1cf334c2f78cc822f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python >=2.7
    - setuptools

test:
  imports:
    - setupmeta

about:
  home: https://github.com/zsimic/setupmeta
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simplify your setup.py
  description: |
    Writing a setup.py typically involves lots of boilerplate and copy-pasting from project to project.
    This package aims to simplify that and bring some DRY principle to python packaging. For more
    information and examples, please refer to: https://github.com/zsimic/setupmeta.
    This package is only required to enable the building of Conda Python packages that
    make use of setupmeta (which is otherwise ordinarily installed dynamically
    as part of the setup.py workflows).
  doc_url: https://github.com/zsimic/setupmeta
  dev_url: https://github.com/zsimic/setupmeta

extra:
  recipe-maintainers:
    - zsimic
    - matthewwardrop
